### ISSUE TITLE
Moveit servo node

### ISSUE THREAD

**Issue by skpawar1305** [Kinovarobotics/ros2_kortex#168]
with the provided servo.yaml, after changing
		ee_frame_name: tool_frame -> end_effector_link
	        command_out_topic: /position_controller/joint_trajectory -> /joint_trajectory_controller/joint_trajectory
with low_latency_mode: true (gamepad publishes at 20 hz) it shakes a lot while moving.
to compensate for that, if I change to low_latency_mode: false, with publish_period: 1/100, it says that very close to singularity very often, and just moves down (without further input)
has anyone used servo node with gen3?

**Comment by moriarty** [comment]
Yes actually we didn't include a launch file or instructions for Servo because we intend to fix servo for this upstream in MoveIt. Other Arms do internal filtering which is why you don't see shaking on the other arms, but the Kinova is following the commands as output by Servo.

**Comment by skpawar1305** [comment]
https://github.com/ros-planning/moveit2/pull/2594
looks like this is solved?

**Comment by skpawar1305** [comment]
it indeed fixes this issue👍
