### ISSUE TITLE
Incorrect joint limits in description

### ISSUE THREAD

**Issue by mserranunes** [Kinovarobotics/ros2_kortex#179]
Hi!

I believe the joint limits in the robot's description do not correspond to the ones indicated in the manual. 
This issue has been fixed in ros_kortex [commit d8f9cc3](https://github.com/Kinovarobotics/ros_kortex/commit/d8f9cc38f99062053fcedc2ff64481dc2e7fbab0) but not in this repo.

Thank you in advance!

**Comment by aalmrad** [comment]
Hello @m-serra,

Thank you for pointing that out. A pull request was submitted [here](https://github.com/Kinovarobotics/ros2_kortex/pull/241)
