### ISSUE TITLE
twist_controller does not currently work in simulation

### ISSUE THREAD

**Issue by dyackzan** [Kinovarobotics/ros2_kortex#182]
The interface that the twist_controller looks for `tcp/twist...` does not exist in simulation. Add a note in the README usage section to let users know

Error when attempting to switch to twist_controller in sim:
```
[ruby $(which ign) gazebo-7] [ERROR] [1698431966.919867932] [controller_manager]: Can't activate controller 'twist_controller': Command interface with 'tcp/twist.linear.x' does not exist
```

**Comment by kevin-andromeda** [comment]
@dyackzan Did you find a workaround?

**Comment by s-m-asjad** [comment]
@kevin-andromeda I do not think a workaround has occurred yet. I still see the issue when I run the service call.
