### ISSUE TITLE
minor correction in installation readme Step 4

### ISSUE THREAD

**Issue by sritank** [Kinovarobotics/ros2_kortex#185]
change Step 4 of install to import simulation.humble.repos instead of simulation.repos. The colcon build failed when using master branches of simulation.repos repositories.

I've also created a pull request for the same if that's more convenient.

**Comment by smoya23** [comment]
Hi @sritank,

This is only true for an user on ROS2 Humble. We will soon push an update on the instructions that will include specific instructions for each distro. I will close this issue as it is in our pipeline to resolve this, but don't hesitate to open a new issue if there is something else. 

Best,
Santiago
