### ISSUE TITLE
Problem installing the ros2 kortex repository

### ISSUE THREAD

**Issue by maria3791** [Kinovarobotics/ros2_kortex#214]
Hello, I recently started my studies on robotic manipulators and intend to perform some simulations using the Kinova Gen3. I apologize in advance if my question is something simple to resolve.

I used this ros2_kortex repository to try to simulate the Kinova Gen3 in Gazebo. However, in item 4 ("To simulate the robot with ignition or gazebo make sure to pull and build additional packages") of the "Contributing to this repository or building from source" topic, I encountered several errors and couldn't proceed.

I tested on ROS 2 Humble, Iron, and Rolling, and even manually installed the gz-math7, gz-transport12, gz-sim7 libraries, and still couldn't proceed at this stage.

I recorded a video demonstrating the step-by-step installation process and would like to get help to solve it. Here is the link to the video: https://youtu.be/0evkE93O1YI

When performing the tests provided in the "Usage" topic, I encountered the error shown in the attached image.
![error2](https://github.com/Kinovarobotics/ros2_kortex/assets/166621732/8fe43454-7c4f-4bbe-b554-62d9222c7587)
![error](https://github.com/Kinovarobotics/ros2_kortex/assets/166621732/3c710b41-4f5b-4702-a1c9-e400ec89e3a7)

**Comment by smoya23** [comment]
Hi @maria3791 ,

I believe we solved your problem through our support system (when you write to support@kinova.ca). The issue was that our build from source instructions were missing some steps, the update has now been merged. I will close this issue, don't hesitate to open another one if you have any other issues.

Cheers,
Santiago
