### ISSUE TITLE
Get the error Invalid parameter "isaac_joint_commands" when building from source

### ISSUE THREAD

**Issue by Reagan1311** [Kinovarobotics/ros2_kortex#216]
Hi there, the following error is encountered when executing the command in the Usage section. I followed the instructions to build from source step by step. Any idea why?

[ERROR] [launch]: Caught exception in launch (see debug for traceback): Invalid parameter "isaac_joint_commands"

**Comment by smoya23** [comment]
Hi @Reagan1311,

Can you try to build again but following the updated instructions in this [PR](https://github.com/Kinovarobotics/ros2_kortex/pull/215) ? There are some missing steps in the current instructions, which I'm pretty sure is the cause of your error. Let me know how it goes and if you get any other error.

Best,
Santiago

**Comment by smoya23** [comment]
PR was merged, you should be able to make it work now by following the instructions of our ReadMe file

**Comment by Reagan1311** [comment]
Thanks a lot, will try it again
