### ISSUE TITLE
Cannot install os-rolling-kortex-bringup in ROS running in docker container

### ISSUE THREAD

**Issue by deepdeep47** [Kinovarobotics/ros2_kortex#236]
Hi there, 
I cannot install the kortex bringup in rolling distro
It shows Unable to locate package ros-rolling-kortex-bringup
Anyway to get through this? Or I have to build it from source?

Thanks you

ROS system:
rolling distro in docker container in Ubuntu, Raspberry Pi

**Comment by martinleroux** [comment]
Hi @deepdeep47 ,
Although you may be able to build it from source, as of today we do not officially support Rolling.

**Comment by aalmrad** [comment]
Closing due du inactivity - reply to the thread if you need the issue to be reopened
