### ISSUE TITLE
Need to upgrade hardware driver to use joint_state_broadcaster

### ISSUE THREAD

**Issue by MarqRazz** [Kinovarobotics/ros2_kortex#36]
When using this repo with Studio rosdep automatically installs the older version of the `joint_state_controller` package (vs. the new `joint_state_broadcaster` package that replaced it), which is still available on Rolling but a rather fragile situation!

**Comment by aalmrad** [comment]
Hello, apologies for the late reply, we recently started tackling the github issues on our repositories more actively. The `joint_state_broadcaster` version 2.37.3 is now used with ros2 humble. I will consider this issue as solved, please reopen the thread if further issues arise.

Best,
Abed
