### ISSUE TITLE
Auto setup of robot_ip fails

### ISSUE THREAD

**Issue by ParthasarathyBana** [Kinovarobotics/ros2_kortex#37]
When the IP address of the Kinova gen3 arm is changed, this file: `ros2_kortex/kortex2_driver/src/hardware_interface.cpp` does not auto update the newest IP address. Due to this, the robot always points to the old IP address and does not communicate with the user. There seems to be a TODO action comment that needs to be completed in the `.cpp` file to solve this. Not sure if doing that would solve it.

**Comment by aalmrad** [comment]
the robot's IP address is now extracted from the "robot_ip" argument so this issue is considered solved. Reopen this thread if further issues arise.
