### ISSUE TITLE
Optimize this part of driver to be more readable.

### ISSUE THREAD

**Issue by destogl** [Kinovarobotics/ros2_kortex#43]
Does this segment really needs to be like this? It is very ugly and seems that things are duplicated. We have to simplify this in the future.

_Originally posted by @destogl in https://github.com/PickNikRobotics/ros2_kortex/pull/41#discussion_r743745178_

**Comment by aalmrad** [comment]
Closing due to insufficient details - reply to the thread if you need the issue to be reopened
