### ISSUE TITLE
Document available Kortex Modes

### ISSUE THREAD

**Issue by destogl** [Kinovarobotics/ros2_kortex#45]
Could you add a short description about available modes? From the old code is this not very clear.

_Originally posted by @destogl in https://github.com/PickNikRobotics/ros2_kortex/pull/41#discussion_r743810944_

**Comment by moriarty** [comment]
The Documentation can be found in the Kortex API.
It is best to keep the documentation near to the source.

In #132 I added
> ROS2 Kortex is the official ROS2 package to interact with Kortex and its related products. It is built upon the Kortex API, documentation for which can be found in the [GitHub Kortex repository](https://github.com/Kinovarobotics/kortex).

specifically the information you're looking for is here:

https://github.com/Kinovarobotics/kortex/blob/master/linked_md/cpp_servoing_modes.md
