### ISSUE TITLE
Add things that has to be executed only once into on_activate method. Check if this is feasible.

### ISSUE THREAD

**Issue by destogl** [Kinovarobotics/ros2_kortex#46]
If this is something that has to be done only once. Would it be appropriate to do it in the `on_activate` method? This would make things simpler here and for sure simpler to debug.

_Originally posted by @destogl in https://github.com/PickNikRobotics/ros2_kortex/pull/41#discussion_r743813672_

**Comment by aalmrad** [comment]
Closing due to insufficient details- reply to the thread if you need the issue to be reopened
