### ISSUE TITLE
Add gripper conversion constants as parameter

### ISSUE THREAD

**Issue by livanov93** [Kinovarobotics/ros2_kortex#61]
This looks like a value which is gripper specific. Does it make sense to add a parameter for it?

_Originally posted by @destogl in https://github.com/PickNikRobotics/ros2_kortex/pull/59#discussion_r755144508_

When using internal communication for gripper control (e.g. robotiq_2f_85) there is a constant which does conversion from radians into percentages and vice versa.

**Comment by aalmrad** [comment]
Closing due to insufficient details - reply to the thread if you need the issue to be reopened
