### ISSUE TITLE
Move fault_controller to picknik_controllers

### ISSUE THREAD

**Issue by moriarty** [Kinovarobotics/ros2_kortex#82]
https://github.com/PickNikRobotics/ros2_kortex/blob/454e89fa1fd3acd8141a5518f8e1dc6f4bc03121/kortex2_controllers/src/fault_controller.cpp#L24

**Comment by moriarty** [comment]
https://github.com/PickNikRobotics/picknik_controllers

Based on discussion and a meeting with the maintainers of ros2_controllers we are first moving this into another open source repository and planning to eventually move it into ros2_controllers from there.

related to #83

**Comment by abake48** [comment]
Officially complete with this PR https://github.com/PickNikRobotics/ros2_kortex/pull/143
